---
title: "CE_Model"
author: "Sarah Klain"
date: "October 23, 2015"
output: 
  html_document: 
    keep_md: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("/Users/sarahklain/Documents/R_2015/wf_ce/CE")

library(ggplot2)
library(ggthemes)
library(wesanderson)
library(viridis)
suppressMessages(library(dplyr))
library(knitr)
library(tidyr)
library(broom)
#install.packages("support.CEs")
library(support.CEs)
# install.packages("xlsx")
library(xlsx)
```

load choice experiment responses data

```{r}
d <- read.csv("~/Documents/R_2015/wf_ce/CE/2015_10_23_WF_CE.csv")
```

Figure out how the data should be formatted.

```{r}
des1 <- rotation.design(
 attribute.names = list(
  hab_qual = c("big loss", "small loss", "small gain", "big gain"), 
  own = c("state", "municipal", "private", "cooperative"), 
  vis = c("mi1", "mi4", "mi8", "mi10"), 
  bill  = c("1", "5", "10", "20")), 
 nalternatives = 2,
 nblocks = 4,
 row.renames = FALSE, 
 randomize = TRUE,
 seed = 987)

des1
```

The format for the design matrix

```{r}
desmat1 <-make.design.matrix(
  choice.experiment.design = des1,
  optout = TRUE,
  categorical.attributes = c("hab_qual", "own", "vis"), 
  continuous.attributes = c("bill"),
  unlabeled = TRUE)

desmat1
write.xlsx(desmat1, "desmat1.xlsx")
```
str(desmat1)

manually match my JMP CE configuration to the desmat1 format
```{r}
desmat2 <- read.xlsx("desmat2", 1)

```

The R CE package did not include the the first level of each attribute. I manually insterted it into the excel sheet, then copy and pasted as values. 

```{r}
desmat3 <- read.csv("desmat3.csv")
str(desmat3)
str(desmat1)
```

Convert integer to numeric

```{r}
desmat3$X <- as.numeric(desmat3$X)
desmat3$BLOCK <- as.numeric(desmat3$BLOCK)
desmat3$QES <- as.numeric(desmat3$QES)
desmat3$ALT <- as.numeric(desmat3$ALT)
desmat3$ASC <- as.numeric(desmat3$ASC)
desmat3$big.loss <- as.numeric(desmat3$big.loss)
desmat3$small.loss <- as.numeric(desmat3$small.loss)
desmat3$small.gain <- as.numeric(desmat3$small.gain)
desmat3$big.gain <- as.numeric(desmat3$big.gain)
desmat3$state <- as.numeric(desmat3$state)
desmat3$municipal <- as.numeric(desmat3$municipal)
desmat3$private <- as.numeric(desmat3$private)
desmat3$cooperative <- as.numeric(desmat3$cooperative)
desmat3$mi1 <- as.numeric(desmat3$mi1)
desmat3$mi4 <- as.numeric(desmat3$mi4)
desmat3$mi8 <- as.numeric(desmat3$mi8)
desmat3$mi10 <- as.numeric(desmat3$mi10)
desmat3$bill <- as.numeric(desmat3$bill)
str(desmat3)
```

```{r}

```


