---
title: "National Polling"
author: "Sarah Klain"
date: "October 29, 2015"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggthemes)
library(viridis)
suppressMessages(library(dplyr))
library(knitr)
library(tidyr)
library("RColorBrewer")
```

```{r}
setwd("/Users/sarahklain/Documents/R_2015/wf_ce/island")

nw <- read.csv("nat_sur_wind.csv")
```

```{r}

nwt <- nw %>% 
  tbl_df

#national wind poll reordered and arranged in descending order
#desc

nwt_d <-  nwt %>%
  arrange(Response, (Response))

ar <-  nwt %>% mutate(Opinion = reorder(Opinion, desc(Response))) %>% 
  arrange(Response)

ar

ns <- ggplot(ar, aes(x = Opinion, y = Response, fill = Opinion))+
  geom_bar(stat = "identity") +
  scale_fill_viridis(discrete=TRUE, "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Opinion") + ylab("Response (%)") +
  ggtitle("Do you think that making electricty\nfrom wind is a good idea, a bad idea,\nor neither good nor bad?")

ns

ggsave(ns, file = "natl_sur_Krosnick.pdf")
```

support by Political party 
```{r}
nc <- read.csv("Not_coded_2015_10_20_WF_CE.csv")

nc$att_w_US2 <- factor(nc$att_w_US, levels=c("Very positive","Positive", "Neutral", "Negative", "Very Negative"))

nc$pol_party2 <- factor(nc$pol_party, levels = c("Republican party", "Democratic party", "Independent", "None", "Other (please specify)"))


#myColors <- brewer.pal(5,"Set1")
#myColors

myColors2 <- c("brown3", "blue3", "gold2", "forestgreen", "darkorchid4")

#names(myColors) <- levels(nc$pol_party)
#colFill <- scale_fill_manual(name = "grp",values = myColors)

colFill2 <- scale_fill_manual(values = myColors2, "")

p <- ggplot(dat,aes(x,y,colour = grp)) + geom_point()
p1 <- p + colFill

attUS <- ggplot(data = nc, aes(x= nc$att_w_US2, fill = pol_party2)) +
  geom_bar() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Attitude") + ylab("Count") + 
  colFill2 + 
  ggtitle("What is your attitude toward developing\nwind power in the US?")
  
attUS

ggsave(attUS, file = "attUS.pdf")
```

Ashlee's code for specifying color in stacked bar chart. 

```{r}
############# Stacked Bar Plot with Colors and Legend - splitting into pos, neutral, negative
# creates a 5 x 5 inch image
png(paste(directory, "WSA_ResponsetoConsult_bargraph.png", sep = ""),         # create PNG for the heat map        
    width = 20*300,        # 5 x 300 pixels
    height = 10*300,
    res = 600,            # 300 pixels per inch
    pointsize = 6)        # smaller font size

op <- par(mar = c(10,2,4,12) + 2) # increase margins, especialy x axis margins

plot <- barplot(as.matrix(percent.happy[,3:18]), main = "Response to Consultation Process",
                col = (colorRampPalette(c("dark blue", "light blue"))(n = 3)), 
                #bty='L',
                axes = FALSE, axisnames = FALSE)

par(op)        # resize area
# add legend in top left outside of plot area
par(xpd=TRUE)
legend(19.5,100, legend = c("Negative", "Offered Suggestion", "Positive"), 
       fill = (colorRampPalette(c("light blue", "dark blue"))(n = 3)), title="Response")

# add x labels
text(plot, par("usr")[3]-.5, labels = (colnames(percent.happy)[c(3:18)]),srt = 45,
     adj = c(1.3,1.3), xpd = TRUE, cex=1)
axis(2)

# Add y axis label
title(main = NULL, sub = NULL, 
      xlab = NULL, ylab = "Percent of Respondents in Stakeholder Group", cex = 1)

# Add in numbers to top of bar graph showing percent in stakeholder group that responded
text(x = plot, y = 100+2, labels=(percent.response), xpd=TRUE)
dev.off()
```

